name: Check conventional commits

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  commit_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: webiny/action-conventional-commits@v1.0.3
